#!/usr/bin/env python
#
# Module: yangop-vrrp-garp
# 
# **** License ****
#
# Copyright (c) 2019 AT&T Intellectual Property.
# All rights reserved.
#
# Copyright (c) 2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# Author: Lorenzo Martinico 
# Date: July 2016
# Description: Script to trigger on demand GARP from rpc call
# 
# SPDX-License-Identifier: GPL-2.0-only
#
# **** End License ****

import json, os, sys

rpc = json.load(sys.stdin)
interface = rpc["interface"] 
group = str(rpc["group"])
os.system("/opt/vyatta/sbin/send-garp " + interface + " " + group)
# Empty response required by RPC
print('{}')
