#! /usr/bin/python3

# Copyright (c) 2019-2020 AT&T Intellectual Property.
# All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only

class Keepalived(object):

    def __init__(self, new_config):
        print("Got new config")
        self.config_string = """
#
# Autogenerated by /opt/vyatta/sbin/vyatta-vrrp-vci
#


global_defs {
        enable_traps
        enable_dbus
        snmp_socket tcp:localhost:705:1
        enable_snmp_keepalived
        enable_snmp_rfc
}
    """

if __name__ == "__main__":
    print("test")
