#! /usr/bin/python3

# Copyright (c) 2019-2020 AT&T Intellectual Property.
# All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only

import vci
import vyatta.vyatta_vrrp_vci as vrrp

if __name__ == "__main__":
    url = "net.vyatta.vci.vrrp"
    namespace_v1 = "vyatta-vrrp-v1"
    (vci.Component(url)
        .model(vci.Model("{}.v1".format(url))
               .config(vrrp.Config())
               .state(vrrp.State())
               .rpc(namespace_v1, "garp", vrrp.send_garp)
               .rpc(namespace_v1, "rfc-intf-map", vrrp.find_recv_intf))
        .run()
        .wait())
